AllCops:
  TargetRubyVersion: 2.6.6
  Exclude:
    - "Gemfile"
    - "cider-ci/**/*"
    - "config/**/*"
    - "db/**/*"
    - "datalayer/**/*"
    - "scripts/**/*"
    - "bin/**/*"
    - "dev/**/*"
    - "tmp/**/*"
    - "test/**/*"
    - "vendor/**/*"

    - "app/models/**/*"
    - "app/channels/**/*"
    - "app/controllers/**/*"
    - "app/graphql/schema.graphql"

Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
