jobs:
  rspec-tests:
    name: "RSpec Tests"
    run_when: &DEFAULT_TRIGGERS
      the branch does not match no-ci or _wip_:
        type: branch
        include_match: &default_branch_match ^.+$
        exclude_match: &default_branch_exclude ^(.*no-ci.*)|([a-z]*_wip_.*)$
    context:
      include: cider-ci/rspec-tests.yml

  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  # META JOBS (only depend on other jobs)                                           #
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

  all-tests:
    name: "All tests"
    description: |
      This job depends on all unit jobs that need to pass.
      It is depended upon by the super-project!
      *Note that there still be more requirements for actually pushing to `origin`,
      look in job **"Good to Merge"**!*
    priority: 999 # "empty" job = high priority
    context:
      task: "echo '✔︎ All dependencies have passed' ; exit 0"
    depends_on: &ALL_TEST_DEPENDS
      rspec-tests: { job_key: rspec-tests, type: job, states: [passed] }
      all-tests of the datalayer:
        {
          job_key: all-tests,
          type: job,
          submodule: [datalayer],
          states: [passed],
        }
    run_when: *ALL_TEST_DEPENDS

  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  # GITHUB BRANCH PROTECTION                                                        #
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

  good-to-merge:
    name: "⚑ Good To Merge"
    description: |
      This job depends on all jobs that need to pass for "Delivery".
      It is depended upon by GitHub's branch protection (for `master`)!
    priority: 999 # "delivery" job = high priority
    context:
      task: "echo '✔︎ All dependencies have passed' ; exit 0"
      # TODO: enable when datalayer is upgraded to newest ruby/rails
      # include:
      #   - path: cider-ci/context-components/merge-checks.yml
      #     submodule: [datalayer]
    run_when:
      always: { type: branch, include_match: "^.+$" }
      all-tests: { job_key: all-tests, type: job, states: [passed] }
    depends_on:
      all-tests: { job_key: all-tests, type: job, states: [passed] }
      # TODO: enable when datalayer is upgraded to newest ruby/rails
      # good to merge of the datalayer:
      #   {
      #     job_key: good-to-merge,
      #     type: job,
      #     submodule: [datalayer],
      #     states: [passed],
      #   }
