test:
  madek_url: https://medienarchiv.zhdk.ch
  locale: 'de'

development:
  madek_url: https://medienarchiv.zhdk.ch
  locale: 'de'

production:
  madek_url: https://medienarchiv.zhdk.ch
  locale: 'de'
